name: ted
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - async_generator=1.10
  - asynctest=0.13.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - cryptography=3.4.8
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.3
  - flatbuffers=2.0.0
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fsspec=2022.1.0
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=3.6.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.3
  - imagecodecs=2021.8.26
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.2
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jxrlib=1.1
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - locket=0.2.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - networkx=2.6.3
  - notebook=6.4.6
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1m
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.4.3
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.20
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyzmq=22.3.0
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.18.3
  - scipy=1.7.3
  - send2trash=1.8.0
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.37.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - antlr4-python3-runtime==4.8
    - clang==11.0
    - cython==0.29.26
    - dm-control==0.0.322773188
    - dm-env==1.5
    - dm-tree==0.1.6
    - fasteners==0.17.3
    - future==0.18.2
    - glfw==2.5.0
    - gym==0.21.0
    - hydra-core==0.11.3
    - imageio==2.14.1
    - imageio-ffmpeg==0.4.5
    - ipdb==0.13.9
    - joblib==1.1.0
    - keras==2.7.0
    - kornia==0.6.2
    - labmaze==1.0.5
    - lxml==4.7.1
    - mock==4.0.3
    - mujoco-py==2.1.2.14
    - omegaconf==1.4.1
    - opencv-python==4.5.5.62
    - pillow==9.0.0
    - pip==21.3.1
    - pyopengl==3.1.5
    - pyparsing==3.0.7
    - pyyaml==6.0
    - scikit-learn==1.0.2
    - setuptools==60.5.0
    - sklearn==0.0
    - tb-nightly==2.9.0a20220127
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tqdm==4.62.3
    - wheel==0.37.1
    - yapf==0.32.0
